

server:
  port: 8080

logging:
  level:
    dev.langchain4j: debug

langchain4j:
  open-ai:
    embedding-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${QWKEY}
      model-name: text-embedding-v4
      log-requests: true
      log-responses: true
      dimensions: 1024

