#langchain4j:
#  open-ai:
#    streaming-chat-model:
#      base-url: https://api.deepseek.com
#      api-key: ${OPEN_API_KEY}
#      model-name: deepseek-reasoner
#      log-requests: true
#      log-responses: true
#      return-thinking: true
#    chat-model:
#      base-url: https://api.deepseek.com
#      api-key: ${OPEN_API_KEY}
#      model-name: deepseek-reasoner
#      log-requests: true
#      log-responses: true
#      return-thinking: true


server:
  port: 8080

logging:
  level:
    dev.langchain4j: debug