langchain4j:
  open-ai:
    chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${QWKEY}
      model-name: qwen3-vl-plus
      log-requests: true
      log-responses: true
      return-thinking: true




logging:
  level:
    dev.langchain4j: debug